Boot Round: 1
Main Path: /home/jordan/Desktop/andrew_nih/Annot
Number of behaviors for Test Set:
  new:
    Alc:
      drink:
      - 1
      - 25
      eat:
      - 6
      - 455
      eathand:
      - 6
      - 666
      groom:
      - 5
      - 3670
      hang:
      - 0
      - 0
      none:
      - 0
      - 0
      rear:
      - 1
      - 55
      rest:
      - 2
      - 59
      sniff:
      - 13
      - 1610
      walk:
      - 4
      - 204
    Trap2:
      drink:
      - 1
      - 35
      eat:
      - 4
      - 2960
      eathand:
      - 9
      - 1195
      groom:
      - 26
      - 6070
      hang:
      - 0
      - 0
      none:
      - 0
      - 0
      rear:
      - 2
      - 54
      rest:
      - 18
      - 15225
      sniff:
      - 58
      - 11678
      walk:
      - 10
      - 488
  old:
    Alc:
      drink:
      - 0
      - 0
      eat:
      - 1
      - 505
      eathand:
      - 99
      - 557
      groom:
      - 53
      - 4438
      hang:
      - 0
      - 0
      none:
      - 0
      - 0
      rear:
      - 0
      - 0
      rest:
      - 13
      - 4972
      sniff:
      - 59
      - 310
      walk:
      - 0
      - 0
    None:
      drink:
      - 2
      - 110
      eat:
      - 5
      - 914
      eathand:
      - 4
      - 437
      groom:
      - 10
      - 133
      hang:
      - 5
      - 611
      none:
      - 0
      - 0
      rear:
      - 2
      - 180
      rest:
      - 0
      - 0
      sniff:
      - 19
      - 707
      walk:
      - 2
      - 175
